/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Detailed representation of the AuthenticationProtocol
 */
export interface AuthenticationProtocol { 
    /**
     * The internal id.
     */
    id?: number;
    /**
     * The human-readable name of the protocol.
     */
    name?: string;
    /**
     * The technical type of protocol, from those supported by Jooxter.
     */
    type?: AuthenticationProtocolTypeEnum;
    /**
     * Entity id of the SAML2 protocol
     */
    entityId?: string;
    /**
     * Provider name cognito
     */
    cognitoFederationName?: string;
    /**
     * The Client ID used to authenticate against the OIDC provider
     */
    clientId?: string;
    /**
     * The Client Secret associated with the OIDC client
     */
    clientSecret?: string;
    /**
     * The Issuer URL of the OIDC provider
     */
    issuerUrl?: string;
}
export enum AuthenticationProtocolTypeEnum {
    Jooxter = 'JOOXTER',
    Saml2 = 'SAML2',
    Oidc = 'OIDC'
};



