/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingAttendeesRequest } from './bookingAttendeesRequest';
import { BookingDateTime } from './bookingDateTime';
import { ParticipationStatusAttendeeDto } from './participationStatusAttendeeDto';
import { BookingOptionRequest } from './bookingOptionRequest';


export interface BookingRequest { 
    /**
     * The summary
     */
    summary: string;
    /**
     * The detailed description
     */
    description?: string;
    /**
     * The booking color. Hexadecimal format
     */
    color: string;
    /**
     * The visibility
     */
    visibility: BookingRequestVisibilityEnum;
    /**
     * The rrule defining the recurrence if any
     */
    rrule?: string;
    start: BookingDateTime;
    end: BookingDateTime;
    /**
     * The resource where the booking takes place
     */
    resourceId: number;
    /**
     * Booking organizer
     */
    organizerId: number;
    /**
     * Number of physical attendees
     */
    physicalAttendees?: number;
    attendees: BookingAttendeesRequest;
    /**
     * The list of attendees : email and participation status
     */
    participationStatusAttendees?: Array<ParticipationStatusAttendeeDto>;
    /**
     * The list of selected options
     */
    options: Array<BookingOptionRequest>;
}
export enum BookingRequestVisibilityEnum {
    Public = 'PUBLIC',
    Private = 'PRIVATE'
};



