/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * End time of the booking
 */
export interface BookingDateTime { 
    /**
     * The date time. In UTC format.
     */
    dateTime: string;
}

