/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represent a set of capabilities on a booking.
 */
export interface BookingCapabilities { 
    /**
     * Whether the principal can checkin the booking or not
     */
    checkin?: boolean;
    /**
     * Whether the principal can checkout the booking or not
     */
    checkout?: boolean;
    /**
     * Whether the principal can cancel the booking or not
     */
    cancel?: boolean;
    /**
     * Whether the principal can update the booking or not
     */
    update?: boolean;
    /**
     * Whether the principal can approve the booking or not
     */
    approve?: boolean;
    /**
     * Whether the principal can answer to a booking invitation
     */
    participate?: boolean;
    /**
     * Whether the principal can confirm his seat in a zone
     */
    arrive?: boolean;
    /**
     * Whether the principal can liberate his seat in a zone
     */
    leave?: boolean;
}

