/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An external action of a booking option.
 */
export interface BookingExternalAction { 
    /**
     * The external action URL
     */
    href: string;
    /**
     * The external action name
     */
    name: string;
    /**
     * The external action type
     */
    type: BookingExternalActionTypeEnum;
}
export enum BookingExternalActionTypeEnum {
    Link = 'LINK'
};



