/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingOptionValue } from './bookingOptionValue';
import { BookingExternalAction } from './bookingExternalAction';


/**
 * Represent the value of the option selected in a booking.
 */
export interface BookingOption { 
    /**
     * ID of this option\'s value
     */
    id?: number;
    /**
     * Option ID, as defined in the resource
     */
    optionId?: number;
    /**
     * Option\'s name
     */
    name?: string;
    picture?: string;
    value?: BookingOptionValue;
    link?: BookingExternalAction;
}

