/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingState } from './bookingState';
import { UserCompressed } from './userCompressed';
import { ResourceCompressed } from './resourceCompressed';
import { BookingTimeBound } from './bookingTimeBound';
import { BookingCapabilities } from './bookingCapabilities';


/**
 * Represent a compressed view of a booking in Jooxter.
 */
export interface BookingCompressed { 
    /**
     * The summary
     */
    summary: string;
    /**
     * The detailed description
     */
    description?: string;
    /**
     * The booking color. Hexadecimal format
     */
    color: string;
    /**
     * The visibility
     */
    visibility: BookingCompressedVisibilityEnum;
    /**
     * The rrule defining the recurrence if any
     */
    rrule?: string;
    start: BookingTimeBound;
    end: BookingTimeBound;
    resource: ResourceCompressed;
    organizer: UserCompressed;
    /**
     * Number of physical attendees
     */
    physicalAttendees?: number;
    checkin?: BookingState;
    checkout?: BookingState;
    approved?: BookingState;
    rejected?: BookingState;
    cancelled?: BookingState;
    /**
     * Booking\'s ID
     */
    readonly id: number;
    /**
     * Booking type
     */
    readonly type?: BookingCompressedTypeEnum;
    /**
     * id of the recurrence source.
     */
    recurrenceSourceId?: number;
    capabilities?: BookingCapabilities;
    icons?: Array<string>;
    participationStatus?: BookingCompressedParticipationStatusEnum;
}
export enum BookingCompressedVisibilityEnum {
    Public = 'PUBLIC',
    Private = 'PRIVATE'
};
export enum BookingCompressedTypeEnum {
    Manual = 'MANUAL',
    Auto = 'AUTO',
    AvailabilityRange = 'AVAILABILITY_RANGE',
    RecurringBooking = 'RECURRING_BOOKING',
    External = 'EXTERNAL',
    ExternalUserEvent = 'EXTERNAL_USER_EVENT'
};
export enum BookingCompressedParticipationStatusEnum {
    Accepted = 'ACCEPTED',
    Declined = 'DECLINED',
    NeedsAction = 'NEEDS_ACTION',
    Tentative = 'TENTATIVE',
    AcceptedRemotely = 'ACCEPTED_REMOTELY'
};



