/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCompressed } from './userCompressed';


/**
 * Represent a state change in a booking.
 */
export interface BookingState { 
    /**
     * The date time of the change. In UTC format.
     */
    at: string;
    by: UserCompressed;
}

