/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Corporation { 
    /**
     * The internal ID
     */
    id?: number;
    /**
     * The name of the corporation
     */
    name: string;
    /**
     * The (postal) address of the corporation
     */
    address: string;
    picture?: string;
    daily_quota?: string;
    readonly remaining_time?: string;
}

