/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkplaceCompressedDto } from './workplaceCompressedDto';


/**
 * The daily workplace
 */
export interface DailyWorkplaceDto { 
    /**
     * The date
     */
    date: string;
    morning: WorkplaceCompressedDto;
    afternoon: WorkplaceCompressedDto;
}

