/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represent an External Attendee in Jooxter.
 */
export interface ExternalAttendee { 
    /**
     * Attendee\'s ID
     */
    id?: number;
    /**
     * Attendee\'s email
     */
    email: string;
    /**
     * Attendee\'s name
     */
    name: string;
    /**
     * Attendee\'s corporation
     */
    corporation?: string;
    /**
     * Whether the attendee has been deactivated or not
     */
    disabled: boolean;
    participationStatus?: ExternalAttendeeParticipationStatusEnum;
    checkin?: string;
    checkout?: string;
}
export enum ExternalAttendeeParticipationStatusEnum {
    Accepted = 'ACCEPTED',
    Declined = 'DECLINED',
    NeedsAction = 'NEEDS_ACTION',
    Tentative = 'TENTATIVE',
    AcceptedRemotely = 'ACCEPTED_REMOTELY'
};



