/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeekCapabilities } from './weekCapabilities';


export interface FeatureCapabilities { 
    collaborators?: boolean;
    resourceManager?: boolean;
    booking?: boolean;
    meetup?: boolean;
    changePassword?: boolean;
    locationManager?: boolean;
    analytics?: boolean;
    week?: WeekCapabilities;
}

