/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * an exceptional closing period for a floor
 */
export interface FloorExceptionalClosingHours { 
    /**
     * title of the floor exception
     */
    title?: string;
    /**
     * start of the floor exception period
     */
    timestampFrom?: string;
    /**
     * end of the floor exception period
     */
    timestampTo?: string;
    /**
     * the floor id for which the period is defined
     */
    floorId?: number;
}

