/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represent a Floor in Jooxter.
 */
export interface Floor { 
    /**
     * Floor unique identifier
     */
    id: number;
    /**
     * Floor elevator number
     */
    number: number;
    /**
     * Floor name
     */
    name: string;
    image?: string;
    /**
     * Scale Pixels Per Meter
     */
    scalePixelsPerMeter?: number;
    /**
     * Scale for a Pictogram
     */
    mapIconScale?: number;
    /**
     * Degrees Relative To North
     */
    degreesRelativeToNorth?: number;
    /**
     * Matrix
     */
    matrix?: string;
}

