/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represent a Location in Jooxter.
 */
export interface LocationRequest { 
    siteId?: number;
    /**
     * Jooxter internal unique id for a location
     */
    readonly id?: number;
    /**
     * The name of the building
     */
    name: string;
    /**
     * The external ID of the building
     */
    externalId?: string;
    /**
     * Path representing a csm localization
     */
    csmLocalizationPath?: string;
    /**
     * The url of the BI for the location
     */
    biLocationUrl?: string;
    /**
     * The full address of the location.
     */
    address: string;
    timezone: string;
    /**
     * Full description
     */
    description?: string;
    /**
     * World latitude, set it or your building will sink in the middle of atlantic ocean.
     */
    latitude?: number;
    /**
     * World longitude, set it or your building will sink in the middle of atlantic ocean.
     */
    longitude?: number;
    /**
     * List of pictures of the location
     */
    pictures?: Array<string>;
    /**
     * Type of the location
     */
    type: LocationRequestTypeEnum;
    /**
     * Location Default
     */
    locationDefault?: boolean;
    /**
     * Perceived Occupancy Duration
     */
    perceivedOccupancyDuration?: number;
    /**
     * Desk Release
     */
    deskRelease?: number;
    url?: string;
    managers?: Array<number>;
}
export enum LocationRequestTypeEnum {
    Building = 'BUILDING',
    Site = 'SITE'
};



