/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationChannel } from './notificationChannel';
import { WorkflowNotificationSettings } from './workflowNotificationSettings';
import { OwnerNotificationSettings } from './ownerNotificationSettings';
import { WorkplaceNotificationSettings } from './workplaceNotificationSettings';
import { BookingNotificationSettings } from './bookingNotificationSettings';
import { InvitationNotificationSettings } from './invitationNotificationSettings';


export interface NotificationSettings { 
    global?: NotificationChannel;
    booking?: BookingNotificationSettings;
    invitation?: InvitationNotificationSettings;
    workplace?: WorkplaceNotificationSettings;
    owner?: OwnerNotificationSettings;
    workflow?: WorkflowNotificationSettings;
}

