/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * a rule defining the opening hours of a resource for a set of days
 */
export interface OpeningHoursRule { 
    /**
     * the id of the resource associated
     */
    resourceId: number;
    timeFrom: string;
    timeTo: string;
    /**
     * list of the days concerned by the rule (short form, case insensitive)
     */
    dayList: OpeningHoursRuleDayListEnum;
    /**
     * date of activation
     */
    startDate: string;
    /**
     * date of deactivation
     */
    endDate: string;
    /**
     * unique identifier of the rule
     */
    readonly ruleId?: number;
}
export enum OpeningHoursRuleDayListEnum {
    Mon = 'mon',
    Tue = 'tue',
    Wed = 'wed',
    Thu = 'thu',
    Fri = 'fri',
    Sat = 'sat',
    Sun = 'sun'
};



