/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OptionDefinitionCompressed } from './optionDefinitionCompressed';


/**
 * Represent an option in Jooxter. One option is available on one resource and rely on an OptionDescription.
 */
export interface Option { 
    definition?: OptionDefinitionCompressed;
    id?: number;
    beforeBookingTime?: number;
    afterBookingTime?: number;
    cancellationPolicyDelayBeforeBooking?: number;
    externalLink?: string;
    defaultValue?: string;
    available?: boolean;
    mandatory?: boolean;
    editable?: boolean;
    selectedByDefault?: boolean;
}

