/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represent a OptionDefinition in Jooxter.
 */
export interface OptionDefinition { 
    id?: number;
    type?: OptionDefinitionTypeEnum;
    name?: string;
    impactBeforeBookingTime?: boolean;
    beforeBookingTime?: number;
    impactAfterBookingTime?: boolean;
    afterBookingTime?: number;
    impactCancellationPolicy?: boolean;
    cancellationPolicyDelayBeforeBooking?: number;
    externalActionType?: OptionDefinitionExternalActionTypeEnum;
    externalActionLabel?: string;
    possibleValues?: Array<string>;
    icon?: string;
}
export enum OptionDefinitionTypeEnum {
    Text = 'TEXT',
    Checkbox = 'CHECKBOX',
    List = 'LIST',
    Textarea = 'TEXTAREA'
};
export enum OptionDefinitionExternalActionTypeEnum {
    Link = 'LINK'
};



