/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The list of attendees : email and participation status
 */
export interface ParticipationStatusAttendeeDto { 
    email: string;
    participationStatus: ParticipationStatusAttendeeDtoParticipationStatusEnum;
}
export enum ParticipationStatusAttendeeDtoParticipationStatusEnum {
    Accepted = 'ACCEPTED',
    Declined = 'DECLINED',
    AcceptedRemotely = 'ACCEPTED_REMOTELY',
    NeedsAction = 'NEEDS_ACTION',
    Tentative = 'TENTATIVE',
    Unknown = 'UNKNOWN'
};



