/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationCompressed } from './locationCompressed';
import { BookingVisibilitySetting } from './bookingVisibilitySetting';
import { ResourceCompressed } from './resourceCompressed';
import { BookingColorSetting } from './bookingColorSetting';


export interface Preferences { 
    lang?: PreferencesLangEnum;
    location?: LocationCompressed;
    resource?: ResourceCompressed;
    timezone?: string;
    defaultBookingColor?: BookingColorSetting;
    defaultBookingVisibility?: BookingVisibilitySetting;
}
export enum PreferencesLangEnum {
    Fr = 'fr',
    En = 'en',
    De = 'de',
    Pt = 'pt',
    Es = 'es',
    It = 'it'
};



