/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingOption } from './bookingOption';
import { BookingState } from './bookingState';
import { UserCompressed } from './userCompressed';
import { ResourceCompressed } from './resourceCompressed';
import { RecurrenceDtoAllOf } from './recurrenceDtoAllOf';
import { BookingCompressed } from './bookingCompressed';
import { BookingTimeBound } from './bookingTimeBound';
import { Booking } from './booking';
import { BookingAttendees } from './bookingAttendees';
import { BookingCapabilities } from './bookingCapabilities';


/**
 * hold data about a booking recurrence
 */
export interface RecurrenceDto { 
    /**
     * The summary
     */
    summary: string;
    /**
     * The detailed description
     */
    description?: string;
    /**
     * The booking color. Hexadecimal format
     */
    color: string;
    /**
     * The visibility
     */
    visibility: RecurrenceDtoVisibilityEnum;
    /**
     * The rrule defining the recurrence if any
     */
    rrule?: string;
    start: BookingTimeBound;
    end: BookingTimeBound;
    resource: ResourceCompressed;
    organizer: UserCompressed;
    /**
     * Number of physical attendees
     */
    physicalAttendees?: number;
    checkin?: BookingState;
    checkout?: BookingState;
    approved?: BookingState;
    rejected?: BookingState;
    cancelled?: BookingState;
    /**
     * Booking\'s ID
     */
    readonly id: number;
    /**
     * Booking type
     */
    readonly type?: RecurrenceDtoTypeEnum;
    /**
     * id of the recurrence source.
     */
    recurrenceSourceId?: number;
    capabilities?: BookingCapabilities;
    attendees: BookingAttendees;
    /**
     * List of selected options
     */
    options: Array<BookingOption>;
    created: BookingState;
    lastModified?: BookingState;
    /**
     * List of all booking occurrences
     */
    occurrences: Array<BookingCompressed>;
    /**
     * show time slots where occurrence can not be created.
     */
    violations: { [key: string]: Array<string>; };
    cancelledOccurrences?: Array<number>;
}
export enum RecurrenceDtoVisibilityEnum {
    Public = 'PUBLIC',
    Private = 'PRIVATE'
};
export enum RecurrenceDtoTypeEnum {
    Manual = 'MANUAL',
    Auto = 'AUTO',
    AvailabilityRange = 'AVAILABILITY_RANGE',
    RecurringBooking = 'RECURRING_BOOKING',
    External = 'EXTERNAL',
    ExternalUserEvent = 'EXTERNAL_USER_EVENT'
};



