/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represent a set of capabilities on a resource.
 */
export interface ResourceCapabilities { 
    /**
     * Whether the principal can book the resource or not
     */
    book: boolean;
    /**
     * Whether the principal can use recurrence on the resource or not
     */
    recurrence: boolean;
    /**
     * Whether the principal can update the resource or not
     */
    update: boolean;
}

