/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * an exceptional opening or closing period for resources
 */
export interface ResourceExceptionalOpeningHours  { 
    /**
     * identifier of the exception
     */
    readonly id?: number;
    /**
     * title of the exception
     */
    title?: string;
    /**
     * start of the exception period
     */
    timestampFrom?: string;
    /**
     * end of the exception period
     */
    timestampTo?: string;
    /**
     * rrule if the exception is a recurrence
     */
    recurrencyRule?: string;
    /**
     * identifier of the first occurence of the exception
     */
    recurrencySource?: number;
    /**
     * the resource id for which the period is defined
     */
    resourceId?: number;
    /**
     * true if the period is an opening one, false for a closing one
     */
    opened?: boolean;
}

