/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceCapabilities } from './resourceCapabilities';
import { BookingPolicy } from './bookingPolicy';
import { ResourceStateDto } from './resourceStateDto';


/**
 * Represent a Resource in Jooxter.
 */
export interface ResourceCompressed { 
    /**
     * the resource internal unique id
     */
    readonly id: number;
    /**
     * The id of the resource type
     */
    resourceTypeId: number;
    /**
     * The id of the resource owner
     */
    ownerId?: number;
    /**
     * The id of the resource location
     */
    locationId: number;
    /**
     * The id of the resource floor
     */
    floorId?: number;
    capabilities?: ResourceCapabilities;
    readonly timezone?: string;
    /**
     * the resource name
     */
    name: string;
    /**
     * the number of people the resource can accept for a booking
     */
    capacity: number;
    /**
     * True if the resource can be booked
     */
    bookable: boolean;
    /**
     * True if the resource is visible on the map or in the search results
     */
    visible: boolean;
    /**
     * True if a booking on the resource must be confirmed by the resource owner
     */
    requestOwnerValidation: boolean;
    /**
     * this fields is deprecated, use bookingPolicy.earliestPolicy instead. The maximum number of minutes allowed before the start of the booking created or modified
     */
    reservationPolicy?: number;
    bookingPolicy?: BookingPolicy;
    /**
     * resource labels
     */
    labels?: Array<string>;
    /**
     * the list of pictures
     */
    pictures?: Array<string>;
    /**
     * email address of resource for cronofy synchronisation
     */
    email?: string;
    /**
     * Resource added to current user\'s favorites
     */
    favorite?: boolean;
    /**
     * True is the checkin is required for a booking on the resource. If it is checked in, the resource will be released
     */
    checkin: boolean;
    state?: ResourceStateDto;
    /**
     * True if a booking must have at least 1 guest
     */
    guestsRequired: boolean;
    /**
     * True if the number of physical attendees is required
     */
    physicalAttendeesRequired: boolean;
}

