/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceTagCompressedDto { 
    /**
     * The device type
     */
    type?: ResourceTagCompressedDtoTypeEnum;
    /**
     * The hardware unique identifier
     */
    hardwareIdentifier?: string;
    /**
     * The resource ID associated to the device
     */
    resourceId?: number;
}
export enum ResourceTagCompressedDtoTypeEnum {
    Tag = 'TAG',
    Pirio = 'PIRIO',
    Sensor = 'SENSOR',
    PeopleCounter = 'PEOPLE_COUNTER',
    MultiActivityLegrand = 'MULTI_ACTIVITY_LEGRAND',
    CountingFlowWired = 'COUNTING_FLOW_WIRED',
    CountingCeilingWired = 'COUNTING_CEILING_WIRED',
    CountingCeilingWirelessV2 = 'COUNTING_CEILING_WIRELESS_V2',
    PresenceCeilingWirelessV2 = 'PRESENCE_CEILING_WIRELESS_V2',
    PresenceDeskWirelessV2 = 'PRESENCE_DESK_WIRELESS_V2',
    PresenceDeskWirelessCi = 'PRESENCE_DESK_WIRELESS_CI',
    PresenceCeilingWirelessCi = 'PRESENCE_CEILING_WIRELESS_CI',
    PresenceDeskWirelessHe = 'PRESENCE_DESK_WIRELESS_HE',
    PresenceCeilingWirelessHe = 'PRESENCE_CEILING_WIRELESS_HE',
    AcsSwitchTof = 'ACS_SWITCH_TOF',
    GwOrange = 'GW_ORANGE',
    GwAxians = 'GW_AXIANS'
};



