/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceTypeRequestDto { 
    /**
     * Resource name
     */
    name: string;
    /**
     * the inner type of the resource type
     */
    metaType: ResourceTypeRequestDtoMetaTypeEnum;
    /**
     * Tell if the type allows to book simultaneously
     */
    allowOverlap: boolean;
}
export enum ResourceTypeRequestDtoMetaTypeEnum {
    Meeting = 'MEETING',
    Desk = 'DESK',
    Booth = 'BOOTH',
    Bubble = 'BUBBLE',
    Parking = 'PARKING',
    Vehicle = 'VEHICLE',
    Visio = 'VISIO',
    Other = 'OTHER'
};



