/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * the type of the resource
 */
export interface ResourceTypeDto { 
    /**
     * Resource type unique identifier
     */
    readonly id: number;
    /**
     * Resource name
     */
    name: string;
    /**
     * Max allowed booking duration
     */
    minDuration?: number;
    /**
     * Minimum allowed booking duration
     */
    maxDuration?: number;
    /**
     * Does the icon should be displayed on map
     */
    showMapIcon: boolean;
    /**
     * Map icon size, 11 is the default
     */
    mapIconSize: number;
    /**
     * Does the recurrence is allowed on this resource type
     */
    recurrency: boolean;
    /**
     * The kind of the pictogram displayed on the map
     */
    picto: ResourceTypeDtoPictoEnum;
    /**
     * the inner type of the type
     */
    metaType?: ResourceTypeDtoMetaTypeEnum;
    /**
     * Tell if the type allows to book simultaneously
     */
    allowOverlap: boolean;
}
export enum ResourceTypeDtoPictoEnum {
    Classic = 'CLASSIC',
    Counter = 'COUNTER',
    Bookable = 'BOOKABLE',
    Unbookable = 'UNBOOKABLE'
};
export enum ResourceTypeDtoMetaTypeEnum {
    Meeting = 'MEETING',
    Desk = 'DESK',
    Booth = 'BOOTH',
    Bubble = 'BUBBLE',
    Parking = 'PARKING',
    Vehicle = 'VEHICLE',
    Visio = 'VISIO',
    Other = 'OTHER'
};



