/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceTimelineStatusDto { 
    /**
     * start
     */
    start: string;
    /**
     * end
     */
    end: string;
    /**
     * status of the event
     */
    status: ResourceTimelineStatusDtoStatusEnum;
}
export enum ResourceTimelineStatusDtoStatusEnum {
    Busy = 'BUSY',
    Closed = 'CLOSED',
    Free = 'FREE',
    Unknown = 'UNKNOWN'
};



