/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceStateDto } from './resourceStateDto';


/**
 * Represent an object Resource with state information 
 */
export interface ResourceFloorDto { 
    /**
     * the resource internal unique id
     */
    id: number;
    /**
     * the resource name
     */
    name: string;
    /**
     * the number of people the resource can accept for a booking
     */
    capacity: number;
    /**
     * the id of resourceType
     */
    resourceTypeId: number;
    state?: ResourceStateDto;
    /**
     * is the resource bookable
     */
    bookable?: boolean;
    /**
     * is the resource favorite
     */
    favorite?: boolean;
}

