/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceRequestDto { 
    /**
     * The resource name
     */
    name: string;
    /**
     * The number of people the resource can accept for a booking, Defaults to 1 if not specified.
     */
    capacity?: number;
    /**
     * Indicates whether the resource can be booked. Defaults to true if not specified.
     */
    bookable?: boolean;
    /**
     * Indicates whether the resource is visible. Defaults to true if not specified.
     */
    visible?: boolean;
    /**
     * Indicates if a booking on the resource must be confirmed by the resource owner.  Defaults to false if not specified.
     */
    requestOwnerValidation?: boolean;
    /**
     * Indicate if a checkin is required for a booking on the resource. Defaults to false if not specified.
     */
    checkin?: boolean;
    /**
     * The description of the resource
     */
    description?: string;
    /**
     * Indicate if a guest is mandatory for a booking on the resource. Defaults to false if not specified.
     */
    guestsRequired?: boolean;
    /**
     * Indicate if a physical attendees is mandatory for a booking on the resource. Defaults to false if not specified.
     */
    physicalAttendeesRequired?: boolean;
    /**
     * Indicate if emails must be sent when booking actions are made on the resource. Defaults to true if not specified.
     */
    sendMailToGuests?: boolean;
    /**
     * The owner id  of the resource
     */
    ownerId?: number;
    /**
     * The location id of the resource
     */
    locationId: number;
    /**
     * The floor id of the resource
     */
    floorId?: number;
    /**
     * The resource type id of the resource
     */
    resourceTypeId?: number;
    /**
     * The group ids assigned to the resource
     */
    groups?: Array<number>;
}

