/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represent a resource current status
 */
export interface ResourceStateDto { 
    occupantsCount?: number;
    /**
     * status of the resource at the present time (BUSY, CLOSED, FREE, UNKNOW
     */
    status?: ResourceStateDtoStatusEnum;
    pictogram?: string;
}
export enum ResourceStateDtoStatusEnum {
    Busy = 'BUSY',
    Closed = 'CLOSED',
    Free = 'FREE',
    Unknown = 'UNKNOWN'
};



