/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Used to get user login details
 */
export interface UserLoginDetail { 
    type?: UserLoginDetailTypeEnum;
    shouldBeMigratedToCognito?: boolean;
    redirect?: string;
    apiVersion?: UserLoginDetailApiVersionEnum;
    cognitoFederatedIdentityProvider?: string;
}
export enum UserLoginDetailTypeEnum {
    Jooxter = 'JOOXTER',
    Saml2 = 'SAML2',
    Oidc = 'OIDC'
};
export enum UserLoginDetailApiVersionEnum {
    V3 = 'V3',
    V4 = 'V4'
};



