/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRequestExtendedLang } from './userRequestExtendedLang';
import { UserGroupCompressed } from './userGroupCompressed';
import { BookingCompressed } from './bookingCompressed';
import { WorkplaceDto } from './workplaceDto';


/**
 * Represent a Jooxter User with workplaces and bookings
 */
export interface UserScheduler { 
    workplaces?: Array<WorkplaceDto>;
    bookings?: Array<BookingCompressed>;
    timezone?: string;
    /**
     * User email
     */
    email: string;
    /**
     * User firstname
     */
    firstname: string;
    /**
     * User lastname
     */
    lastname: string;
    lang?: UserRequestExtendedLang;
    /**
     * User type
     */
    type?: UserSchedulerTypeEnum;
    /**
     * User activation state. Optional. Default to true.
     */
    validation?: boolean;
    /**
     * User ID in an external system
     */
    externalId?: string;
    /**
     * Authentication protocol for the user. Default to account\'s one if not provided
     */
    authenticationProtocolId?: number;
    /**
     * User unique ID
     */
    id: number;
    /**
     * User Location ID
     */
    locationId: number;
    /**
     * User Corporation ID
     */
    corporationId: number;
    /**
     * user groups
     */
    groups: Array<UserGroupCompressed>;
    picture?: string;
    favorite?: boolean;
}
export enum UserSchedulerTypeEnum {
    Manager = 'MANAGER',
    User = 'USER',
    Admin = 'ADMIN',
    OmniVision = 'OMNI_VISION'
};



