/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Corporation } from './corporation';
import { LocationCompressed } from './locationCompressed';
import { UserRequestExtendedLang } from './userRequestExtendedLang';
import { UserGroupCompressed } from './userGroupCompressed';
import { UserCapabilitiesDto } from './userCapabilitiesDto';


/**
 * Represent a Jooxter User
 */
export interface User { 
    id?: number;
    /**
     * User profile
     */
    profile?: string;
    /**
     * User department
     */
    department?: string;
    /**
     * User phone
     */
    telephone?: string;
    /**
     * User registration date
     */
    registrationDate?: string;
    /**
     * User last connexion
     */
    lastConnection?: string;
    timezone?: string;
    location?: LocationCompressed;
    corporation?: Corporation;
    /**
     * user groups
     */
    groups?: Array<UserGroupCompressed>;
    capabilities?: UserCapabilitiesDto;
    picture?: string;
    isFavorite?: boolean;
    iCalendarId?: string;
    /**
     * User has completed the onboarding
     */
    setupDone?: boolean;
    /**
     * User email
     */
    email: string;
    /**
     * User firstname
     */
    firstname: string;
    /**
     * User lastname
     */
    lastname: string;
    lang?: UserRequestExtendedLang;
    /**
     * User type
     */
    type?: UserTypeEnum;
    /**
     * User activation state. Optional. Default to true.
     */
    validation?: boolean;
    /**
     * User ID in an external system
     */
    externalId?: string;
    /**
     * Authentication protocol for the user. Default to account\'s one if not provided
     */
    authenticationProtocolId?: number;
    favorite?: boolean;
    icalendarId?: string;
}
export enum UserTypeEnum {
    Manager = 'MANAGER',
    User = 'USER',
    Admin = 'ADMIN',
    OmniVision = 'OMNI_VISION'
};



