/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User analytics access rights information
 */
export interface UserAnalyticAccessDTO { 
    /**
     * Indicates if the user has access to occupation analytics
     */
    readonly occupation?: boolean;
    /**
     * Indicates if the user has access to booking analytics
     */
    readonly booking?: boolean;
}

