/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRequestExtendedLang } from './userRequestExtendedLang';


export interface UserRequestExtended { 
    /**
     * User email
     */
    email: string;
    /**
     * User firstname
     */
    firstname: string;
    /**
     * User lastname
     */
    lastname: string;
    lang?: UserRequestExtendedLang;
    /**
     * User type
     */
    type?: UserRequestExtendedTypeEnum;
    /**
     * User activation state. Optional. Default to true.
     */
    validation?: boolean;
    /**
     * User ID in an external system
     */
    externalId?: string;
    /**
     * Authentication protocol for the user. Default to account\'s one if not provided
     */
    authenticationProtocolId?: number;
    /**
     * User phone number. Default to null.
     */
    telephone?: string;
    /**
     * User job profile. Default to null.
     */
    profile?: string;
    /**
     * User department. Default to null.
     */
    department?: string;
    /**
     * User Location ID
     */
    locationId?: number;
    /**
     * User Corporation ID
     */
    corporationId?: number;
    /**
     * User picture id
     */
    pictureId?: number;
    /**
     * Timezone of the user
     */
    timezone?: string;
    /**
     * List of groups ID containing the user. Existing groups are replaced with this list.
     */
    groupIds?: Array<number>;
}
export enum UserRequestExtendedTypeEnum {
    Manager = 'MANAGER',
    User = 'USER',
    Admin = 'ADMIN',
    OmniVision = 'OMNI_VISION'
};



