/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCompressed } from './userCompressed';


/**
 * Represent a Jooxter UserGroup
 */
export interface UserGroup { 
    id?: number;
    /**
     * User group name
     */
    name: string;
    /**
     * User group description
     */
    description?: string;
    /**
     * Managers of the Group
     */
    managers?: Set<UserCompressed>;
    /**
     * Related resource groups
     */
    resourceGroups?: Array<number>;
    /**
     * The url of the BI for the user group
     */
    biUserGroupUrl?: string;
}

