/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkplaceRuleRemainingDays { 
    /**
     * The unique identifier of the rule
     */
    workplaceRuleId: number;
    /**
     * Granularity of the rule
     */
    rulePeriod: WorkplaceRuleRemainingDaysRulePeriodEnum;
    /**
     * The location of the rule, in case it is an office rule
     */
    locationId?: number;
    remainingDays: number;
}
export enum WorkplaceRuleRemainingDaysRulePeriodEnum {
    Week = 'WEEK',
    Month = 'MONTH',
    Year = 'YEAR'
};



