/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkplaceCapabilitiesDto } from './workplaceCapabilitiesDto';


/**
 * The workplace compressed
 */
export interface WorkplaceCompressedDto { 
    /**
     * The id of the workplace
     */
    id?: number;
    /**
     * The workplace type
     */
    type: WorkplaceCompressedDtoTypeEnum;
    /**
     * The location of workplace
     */
    locationId?: number;
    capabilities: WorkplaceCapabilitiesDto;
}
export enum WorkplaceCompressedDtoTypeEnum {
    WorkFromHome = 'WORK_FROM_HOME',
    Mission = 'MISSION',
    Office = 'OFFICE',
    Off = 'OFF',
    Unknown = 'UNKNOWN'
};



