/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkplaceRuleDto { 
    /**
     * The unique identifier of the rule
     */
    id: number;
    /**
     * Type of workplaces on which the rule applies
     */
    workplaceType: WorkplaceRuleDtoWorkplaceTypeEnum;
    /**
     * Granularity of the rule
     */
    rulePeriod: WorkplaceRuleDtoRulePeriodEnum;
    /**
     * Maximum value of the rule
     */
    max: number;
    /**
     * The location of the rule, in case it is an office rule
     */
    locationId?: number;
}
export enum WorkplaceRuleDtoWorkplaceTypeEnum {
    WorkFromHome = 'WORK_FROM_HOME',
    Mission = 'MISSION',
    Office = 'OFFICE',
    Off = 'OFF',
    Unknown = 'UNKNOWN'
};
export enum WorkplaceRuleDtoRulePeriodEnum {
    Week = 'WEEK',
    Month = 'MONTH',
    Year = 'YEAR'
};



