/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationCompressed } from './locationCompressed';
import { WorkplaceCapabilitiesDto } from './workplaceCapabilitiesDto';


export interface WorkplaceDto { 
    id?: number;
    /**
     * The start date of workplace (format ISO-8601)
     */
    start: string;
    /**
     * The end date of workplace (format ISO-8601)
     */
    end: string;
    type: WorkplaceDtoTypeEnum;
    location?: LocationCompressed;
    capabilities?: WorkplaceCapabilitiesDto;
}
export enum WorkplaceDtoTypeEnum {
    WorkFromHome = 'WORK_FROM_HOME',
    Mission = 'MISSION',
    Office = 'OFFICE',
    Off = 'OFF',
    Unknown = 'UNKNOWN'
};



