/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The work range of afternoon
 */
export interface WorkHourRange { 
    start: string;
    end: string;
    workplace?: WorkHourRangeWorkplaceEnum;
    readonly generatedByDefault?: boolean;
}
export enum WorkHourRangeWorkplaceEnum {
    WorkFromHome = 'WORK_FROM_HOME',
    Mission = 'MISSION',
    Office = 'OFFICE',
    Off = 'OFF',
    Unknown = 'UNKNOWN'
};



