/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkplaceRequestDto { 
    /**
     * The start date of workplace (format ISO-8601)
     */
    start: string;
    /**
     * The end date of workplace (format ISO-8601)
     */
    end: string;
    /**
     * WORK_FROM_HOME,MISSION,OFFICE,OFF, UNKNOWN
     */
    type: WorkplaceRequestDtoTypeEnum;
    /**
     * The rrule defining the recurrence if any
     */
    rrule?: string;
    /**
     * The location id of workplace (if, and only if workplace type is OFFICE
     */
    locationId?: number;
}
export enum WorkplaceRequestDtoTypeEnum {
    WorkFromHome = 'WORK_FROM_HOME',
    Mission = 'MISSION',
    Office = 'OFFICE',
    Off = 'OFF',
    Unknown = 'UNKNOWN'
};



