/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Capabilities of the principal on the workplace.
 */
export interface WorkplaceCapabilitiesDto { 
    /**
     * Whether the principal can cancel the workplace or not
     */
    cancel?: boolean;
    /**
     * Whether the principal can update the workplace or not
     */
    update?: boolean;
    /**
     * Whether the principal can create the workplace or not
     */
    create?: boolean;
}

