/**
 * Jooxter REST API V3
 * Documentation of Jooxter API. Current version 3.X.X
 *
 * The version of the OpenAPI document: v4
 * Contact: developer@jooxter.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCompressed } from './userCompressed';
import { BestPlace } from './bestPlace';
import { ResourceCompressed } from './resourceCompressed';
import { BookingCompressed } from './bookingCompressed';
import { Interval } from './interval';


export interface WorkTogetherDto { 
    interval?: Interval;
    bestPlace?: BestPlace;
    alreadyBooked?: Array<BookingCompressed>;
    desksToBook?: Array<ResourceCompressed>;
    usersToBook?: Array<UserCompressed>;
}

